config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "callbacks"
  } 

  resources :charges, :only => [:new, :create]

  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

  root 'home#index'  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :author_name, presence: true
  validates :author_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :pic, PicUploader
  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, :through => :taggings

  validates :title, presence: true
  #validates :author, presence: true
  validates :body, presence: true




  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:name).join(", ")
  end
end  

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :omniauthable

  def display_name
    name.blank? ? email : name
  end

  def self.from_omniauth(auth)  
    where(email: auth.info.email).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end 

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post }
        format.json { render json: { comment: render_to_string(@comment, formats: 'html') }}
      else
        format.html { redirect_to :back }
        format.json { render json: { error: "NOPE" } } # TODO actually do error here.
      end
    end
  end


  def destroy
    @comment.destroy
    respond_to do |format|
    format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  #def set_comment
   # @comment = Comment.find(params[:id])
  #end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:post_id, :title, :author_name, :author_email, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").limit(3)
  end

  def show
    @post = Post.find(params[:id])
    #@comment = @post.comments.build
  end
end

app/controllers/posts_controller.rb
  class PostsController < ApplicationController
    #before_action :require_authenticated_user, :except => [:index, :show]
    before_action :set_post, :only => [:show, :edit, :update, :destroy]
    
    def index
     @posts = Post.all.page(params[:page]).per(3)
   end

   def new
     @post = Post.new
     @post = current_user.posts.new
   end

   def show
     @posts = Post.all
     @comment = Comment.new
   end

   def create
     @post = Post.create(post_params)

     if @post.save
       redirect_to @post
     else
       render 'new'
     end
   end

   def edit
   end

   def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :body, :all_tags, :pic)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :json
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email_address, :avatar, :password, :password_confirmation)
  end

end

app/helpers/add_references_helper.rb
module AddReferencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<ul>
  <li class="comment">
    <h4><%= comment.title %></h4>
    <p><%= comment.body %></p>
    <% unless comment.author_name.blank? %>
    <%commentuser = comment.author_name  %>
    <% else %>
    <%commentuser = "user"  %>
    <% end %>
    <p>created by: <%= commentuser%> at <%= comment.created_at.strftime("%B %e %Y %I:%M%p") %></p>
  </li>
</ul>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this comment from being saved:</h2>

  <ul>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :date %><br>
  <%= f.date_select :date, start_year: 1980 %>
</div>
<div class="field">
  <%= f.label :author_email %>
  <%= f.text_field :author_email %>
</div>
<div class="field">
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comments %> 
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<div class="page-header">
<h1>New Comment</h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', comment_path %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_field :body %><br>
  <br>
  <%= f.label :tag %><br>
  <%= f.text_field :all_tags %><br>
  <br>
  <%= f.label :pic %><br>
  <%= f.file_field :pic %><br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @posts, class: "button secondary small" %> 
<%= link_to 'Back', posts_path, class: "button secondary small" %>

app/views/posts/form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select(:person_id, Person.all, :id, :full_name) %>
  </div>  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= paginate @posts %>
    
<div class="row">
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post%></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    <h4 class="all_tags">#<%= link_to post.all_tags %></h5>
    <p class="pic"><%= image_tag(post.pic.thumb) %></p>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: "button secondary small" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="large-12 column">
    <h1 class="title">
      <%= @post.title %> 
    </h1>

    <p class="date">
      Submitted <%= time_ago_in_words(@post.created_at) %> ago        
    </p>

    <p class="body">
      <%= @post.body %>
    </p>

    <p class="all_tags">
      # <%= @post.all_tags %>
    </p>

    <p class="pic">
      <%= image_tag(@post.pic.url) %>
    </p>

    <strong> Comments (<%= @post.comments.size %>):</strong>
    <div id="comment_list">
      <% @post.comments.each do |comment| %>
      <%= render comment %>
      <% end %>      
    </div>
    
    <div class="container">
      <%= form_for([@post, @comment]) do |f| %>
      Title: <%= f.text_field :title %><br>
      Name: <%= f.text_field :author_name %><br>
      Email address: <%= f.text_field :author_email %><br>
      Comment: <%= f.text_area :body %><br>
      <%= f.submit class: "button round secondary small" %>
      <% end %>
    </div>

    <%= link_to 'All Posts', posts_path, class: "button round secondary small" %>