config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "callbacks"
  } 

  resources :charges, :only => [:new, :create]

  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

  root 'home#index'  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :author_name, presence: true
  validates :author_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :pic, PicUploader
  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, :through => :taggings

  validates :title, presence: true
  #validates :author, presence: true
  validates :body, presence: true




  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:name).join(", ")
  end
end  

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :omniauthable

  def display_name
    name.blank? ? email : name
  end

  def self.from_omniauth(auth)  
    where(email: auth.info.email).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end 

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post }
        format.json { render json: { comment: render_to_string(@comment, formats: 'html') }}
      else
        format.html { redirect_to :back }
        format.json { render json: { error: "NOPE" } } # TODO actually do error here.
      end
    end
  end


  def destroy
    @comment.destroy
    respond_to do |format|
    format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  #def set_comment
   # @comment = Comment.find(params[:id])
  #end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:post_id, :title, :author_name, :author_email, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").limit(3)
  end

  def show
    @post = Post.find(params[:id])
    #@comment = @post.comments.build
  end
end

app/controllers/posts_controller.rb
  class PostsController < ApplicationController
    #before_action :require_authenticated_user, :except => [:index, :show]
    before_action :set_post, :only => [:show, :edit, :update, :destroy]
    
    def index
     @posts = Post.all.page(params[:page]).per(3)
   end

   def new
     @post = Post.new
     @post = current_user.posts.new
   end

   def show
     @posts = Post.all
     @comment = Comment.new
   end

   def create
     @post = Post.create(post_params)

     if @post.save
       redirect_to @post
     else
       render 'new'
     end
   end

   def edit
   end

   def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :body, :all_tags, :pic)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email_address, :avatar, :password, :password_confirmation)
  end

end

app/helpers/add_references_helper.rb
module AddReferencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="cup o Duncan">
  <meta name="author" content="Duncan Neal">
  <title><%= content_for?(:title) ? yield(:title) : "cup o Duncan" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header>
  Cup o Duncan  
</header>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
       <div id="navbar" class="navbar-collapse collapse">
        <% unless current_user %> 
        <form class="navbar-form">
          <%= link_to "Sign In", new_user_session_path, :class => "btn btn-default navbar-right" %>
        </form>
        <% else %>
        <form action="<%= destroy_user_session_path %>" method="POST" class="navbar-form navbar-right">
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
          <input name="_method" type="hidden" value="delete" />
          <button type="submit" class="btn round btn-default">Log Out as <%= current_user.display_name %></button>
        </form>  
        <% end %>
        <a class="navbar-brand" href="<%= root_path %>"><h1>Drink!</h1></a>
      </div> 
    </div>
  </nav>

  <%= yield %>

  
  <footer>
  <h6>Like what you read? Make a donation to keep the content flowing!</h6>
  <%= link_to 'Donate', new_charge_path, class: "button round secondary small" %>
    <div class="container">
     <p>&copy; a D2 joint 2015</p>
   </div>
 </footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>